### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by jim-rosales** [ChristianNikodemus/prj-rev-bwfs-tea-cozy#4]
It might be a personal preference to place styles on the same line as the declaration of the rule, but usually, styles go on a new line after the opening `{`

Take a look at this [style guide](https://github.com/airbnb/css) for more recommendations on best practices concerning CSS formatting.

Here is an example:
```CSS
header {
  display: flex;
  position: fixed;
  width: 100%;
  height: 69px;
  border-bottom: 1px solid seashell;
  z-index: 1;
  background-color: black;
  top: 0px;
}
```

https://github.com/ChristianNikodemus/prj-rev-bwfs-tea-cozy/blob/8f10b78688c84a5b4a509c85a681bef8be0bf84a/10%20Tea%20Cozy/resources/css/style.css#L22-L30
